### ISSUE TITLE
Unsupported class file major version 60

### ISSUE THREAD

**Issue by mehmetdelikaya** [centrifugal/centrifuge-java#24]
Hi there, 

I am trying to integrate centrifuge-java into a Android Kotlin based project. I kept getting **java.lang.IllegalArgumentException: Unsupported class file major version 60** compile error for version 0.0.6. 

I am able to get a successful build with version 0.0.5. 

What should be the other versions(gradle, gradle bin) for successful build for 0.0.6?

**Comment by FZambia** [comment]
I was building release with Gradle 7 - see https://github.com/centrifugal/centrifuge-java/blob/master/gradle/wrapper/gradle-wrapper.properties#L6

**Comment by mehmetdelikaya** [comment]
Oh I see, I am gonna keep using gradle 6.5 for a while as some of the libraries are still in Jcenter() which is deprecated by gradle 7. 
Thanks mate

**Comment by FZambia** [comment]
Hmm, I thought that Gradle version used for building does not affect distribution - i.e. only local thing used to upload. Does this all mean that you can not use centrifuge-java 0.0.6 in your project? (I am not a Java developer so may miss some obvious things).

**Comment by SimonHausdorf** [comment]
We are using `0.0.6` with maven and are getting the following error:

```
  bad class file: /Users/***/.m2/repository/io/github/centrifugal/centrifuge-java/0.0.6/centrifuge-java-0.0.6.jar(io/github/centrifugal/centrifuge/Client.class)
    class file has wrong version 60.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

I am posting this here as I think it is related? Version `0.0.5` works without issues.

**Comment by FZambia** [comment]
@SimonHausdorf @mehmetdelikaya I just released v0.0.7 using:
```
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9)
OpenJDK 64-Bit Server VM (build 11.0.10+9, mixed mode)
```

Could you try it?

**Comment by mehmetdelikaya** [comment]
@FZambia @SimonHausdorf  version 0.0.7 worked for me, Thanks man

**Comment by SimonHausdorf** [comment]
When using openjdk 8 I still received the following:

```
class file has wrong version 55.0, should be 52.0
```

switching to openjdk 11 made it work. @mehmetdelikaya guess you can close it as solved :)

**Comment by FZambia** [comment]
Thanks guys!

**Comment by mehmetdelikaya** [comment]
Thank you too

**Comment by mehmetdelikaya** [comment]
Hi guys,

I have faced with an issue with version v0.0.7 and v0.0.8. I was not able to get socket events with signed and obfuscated apk for these two versions. However downgrading to v0.0.5 worked well again.

**Comment by FZambia** [comment]
@mehmetdelikaya hello, open a new issue with detailed steps to reproduce (code, how you are building apk etc. so I could try this locally) – I can not help looking at info you provided.

**Comment by FZambia** [comment]
@mehmetdelikaya [possible reason](https://github.com/centrifugal/centrifuge-java/issues/20#issuecomment-880034181) maybe?

**Comment by mehmetdelikaya** [comment]
@FZambia probably same issue mate. I couldn't come back with the more detailed explanation just wanted to see if it is common or not. Thanks, I will try it with the provided proguard rule.
