### ISSUE TITLE
TimeoutException on Subscription.publish

### ISSUE THREAD

**Issue by codenoid** [centrifugal/centrifuge-java#9]
I'm trying to `publish` a message via onPublish callback, but I'm always getting : 

`/System.out: publish error: java.util.concurrent.TimeoutException`

The code : 

```java
@Override
public void onPublish(Subscription sub, PublishEvent event) {
    String data = new String(event.getData(), UTF_8);
    Log.wtf("INCOMING", "message from " + sub.getChannel() + " " + data);

    try {
        JSONObject welcome = new JSONObject();
        welcome.put("input", "i'm old");
        byte[] msg = welcome.toString().getBytes("UTF-8");
        sub.publish(msg, new ReplyCallback<PublishResult>() {
            @Override
            public void onFailure(Throwable e) {
                System.out.println("publish error: " + e);
            }

            @Override
            public void onDone(ReplyError err, PublishResult reply) {
                if (err != null) {
                    System.out.println("error publish: " + err.getMessage());
                    return;
                }
                System.out.println("successfully published");
            }
        });
    } catch (Exception e) {
        e.printStackTrace();
    }
}
```

but when sending a message via 
```java
client.publish("public", msg, new ReplyCallback<PublishResult>)
```
it's working fine

my centrifugo config : 

```json
{
    "anonymous":true,
    "publish":true,
    "subscribe_to_publish":true,
    "presence":true,
    "join_leave":true,
    "history_size":1500,
    "history_lifetime":300,
    "history_recover":true,
    "history_disable_for_client":false,
    "debug":true,
    "api_insecure":true,
    "log_level":"debug",
    "namespaces":[
        {
            "name":"public",
            "publish":true,
            "anonymous":true,
            "subscribe_to_publish":true,
            "history_size":10,
            "history_lifetime":300,
            "history_recover":true
        }
    ]
}
```

**Comment by FZambia** [comment]
Fix released with 0.0.3

**Comment by frakc** [comment]
Update to 003 still reproduces. 
I can receive events from subscription, but when I publish event I always getting timeout exception

**Comment by FZambia** [comment]
@frakc since i believe that original issue was fixed this can be some other corner case. Could you please provide a minimal code example to reproduce - and I'll check it out.
